# Site settings
title: Dominik Lenhardt IT-Services
description: Effiziente IT-Lösungen, flexibel für Sie gestaltet – Ihr Experte für System- und Cloud-Administration
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "lenhardt-its.github.io"

# User settings
username: Dominik Lenhardt
email: office@lenhardt.cc
twitter_username: OnkelDominik
github_username:  OnkelDom
linkedin_username: dominik-lenhardt-086645226
xing_username: Dominik_Lenhardt
stackoverflow_userid: 17848024
stackoverflow_username: dominik-lenhardt

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
